GET http://localhost:3000/cricket_team/

###

GET http://localhost:3000/cricket_team/1/

###

POST http://localhost:3000/cricket_team/

Content-Type: application/json

{
  "playerName": "Vishal",
  "jerseyNumber": 17,
  "role": "Bowler"
}

###

PUT http://localhost:3000/cricket_team/3/

Content-Type: application/json

{
  "playerName": "Maneesh",
  "jerseyNumber": 54,
  "role": "All-rounder"
}

###

DELETE http://localhost:3000/cricket_team/2/

###
